[package]
name = "nannou_hot_reload"
version = "0.1.0"
authors = ["Jack Foltz <jack@foltz.io>"]
edition = "2018"

[lib]
name = "lib"
path = "src/lib.rs"

[[bin]]
name = "bin"
path = "src/main.rs"

[dependencies]
nannou = "0.13.1"
dynamic_reload = "0.4.0"
